languageCode = 'en-us'
title = '[HUGO] Presentations'
baseURL = './'
relativeURLs = true
canonifyURLs = false


[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
title = true
block = true

[markup.goldmark.extensions]
passthrough = { enable = true, delimiters = { block = [['$$', '$$']], inline = [['$', '$']] } }

[params]
# Default reveal theme.
default_theme = "white"
