languageCode = 'en-us'
title = '[HUGO] Presentations'
baseURL = './'
relativeURLs = true
canonifyURLs = false

[outputFormats]
    [outputFormats.html]
    isPlainText = true

[markup]
    [markup.highlight]
    codeFences = false
    noClasses = true

    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true

        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
            title = true
            block = true

        [markup.goldmark.extensions]
        passthrough = { enable = true, delimiters = { block = [['$$', '$$']], inline = [['$', '$']] } }
        typographer = true

[params]
theme = "white"
code_theme = "base16/nord"
math_engine = "MathJax3"
